#!/bin/bash

k_change_config() {
    kwriteconfig5 --file "$1" --group "$2" --key "$3" $4
}

k_delete_config() {
    kwriteconfig5 --file "$1" --group "$2" --key "$3" --delete
}

if [ $1 == "-c" ]; then
    # Krunner
    k_delete_config "kwinrc" "ModifierOnlyShortcuts" "Meta"

    # Animaciones
    k_delete_config "kdeglobals" "KDE" "AnimationDurationFactor"

    # Google Chrome
    k_delete_config "kglobalshortcutsrc" "google-chrome.desktop" "_launch"

    # Alacritty
    k_delete_config "kglobalshortcutsrc" "Alacritty.desktop" "_launch"

    # Plasmashell
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 1" "Meta+1,Meta+1,Activar la entrada 1 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 2" "Meta+2,Meta+2,Activar la entrada 2 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 3" "Meta+3,Meta+3,Activar la entrada 3 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 4" "Meta+4,Meta+4,Activar la entrada 4 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 5" "Meta+5,Meta+5,Activar la entrada 5 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 6" "Meta+6,Meta+6,Activar la entrada 6 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 7" "Meta+7,Meta+7,Activar la entrada 7 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 8" "Meta+8,Meta+8,Activar la entrada 8 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 9" "Meta+9,Meta+9,Activar la entrada 9 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 10" "Meta+0,Meta+0,Activar la entrada 10 del gestor de tareas"

    # Kwin
    k_change_config "kglobalshortcutsrc" "kwin" "Switch to Desktop 1" "Ctrl+F1,Ctrl+F1,Cambiar al escritorio 1"
    k_change_config "kglobalshortcutsrc" "kwin" "Switch to Desktop 2" "Ctrl+F2,Ctrl+F2,Cambiar al escritorio 2"
    k_change_config "kglobalshortcutsrc" "kwin" "Switch to Desktop 3" "Ctrl+F3,Ctrl+F3,Cambiar al escritorio 3"
    k_change_config "kglobalshortcutsrc" "kwin" "Switch to Desktop 4" "Ctrl+F4,Ctrl+F4,Cambiar al escritorio 4"

    k_change_config "kglobalshortcutsrc" "kwin" "Window to Desktop 1" "none,none,Ventana al escritorio 1"
    k_change_config "kglobalshortcutsrc" "kwin" "Window to Desktop 2" 'none,none,Ventana al escritorio 2'
    k_change_config "kglobalshortcutsrc" "kwin" "Window to Desktop 3" "none,none,Ventana al escritorio 3"
    k_change_config "kglobalshortcutsrc" "kwin" "Window to Desktop 4" "none,none,Ventana al escritorio 4"

    # Aplicar
    qdbus org.kde.KWin /KWin reconfigure
    killall kglobalaccel5
    kglobalaccel5 &

elif [ $1 == "-g" ]; then
    # Krunner
    k_change_config "kwinrc" "ModifierOnlyShortcuts" "Meta" "org.kde.krunner,/App,,toggleDisplay"

    # Animaciones
    k_change_config "kdeglobals" "KDE" "AnimationDurationFactor" "0"

    # Google Chrome
    k_change_config "kglobalshortcutsrc" "google-chrome.desktop" "_launch" "Meta+B,none,Google Chrome"
    k_change_config "kglobalshortcutsrc" "google-chrome.desktop" "_k_friendly_name" "Google Chrome"

    # Alacritty
    k_change_config "kglobalshortcutsrc" "Alacritty.desktop" "_launch" "Meta+T,none,Alacritty"
    k_change_config "kglobalshortcutsrc" "Alacritty.desktop" "_k_friendly_name" "Alacritty"

    # Plasmashell
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 1" "none,Meta+1,Activar la entrada 1 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 2" "none,Meta+2,Activar la entrada 2 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 3" "none,Meta+3,Activar la entrada 3 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 4" "none,Meta+4,Activar la entrada 4 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 5" "none,Meta+5,Activar la entrada 5 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 6" "none,Meta+6,Activar la entrada 6 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 7" "none,Meta+7,Activar la entrada 7 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 8" "none,Meta+8,Activar la entrada 8 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 9" "none,Meta+9,Activar la entrada 9 del gestor de tareas"
    k_change_config "kglobalshortcutsrc" "plasmashell" "activate task manager entry 10" "none,Meta+0,Activar la entrada 10 del gestor de tareas"

    # Kwin
    k_change_config "kglobalshortcutsrc" "kwin" "Switch to Desktop 1" "Meta+1,Ctrl+F1,Cambiar al escritorio 1"
    k_change_config "kglobalshortcutsrc" "kwin" "Switch to Desktop 2" "Meta+2,Ctrl+F2,Cambiar al escritorio 2"
    k_change_config "kglobalshortcutsrc" "kwin" "Switch to Desktop 3" "Meta+3,Ctrl+F3,Cambiar al escritorio 3"
    k_change_config "kglobalshortcutsrc" "kwin" "Switch to Desktop 4" "Meta+4,Ctrl+F4,Cambiar al escritorio 4"

    k_change_config "kglobalshortcutsrc" "kwin" "Window to Desktop 1" "Meta+!,none,Ventana al escritorio 1"
    k_change_config "kglobalshortcutsrc" "kwin" "Window to Desktop 2" 'Meta+",none,Ventana al escritorio 1'
    k_change_config "kglobalshortcutsrc" "kwin" "Window to Desktop 3" "Meta+#,none,Ventana al escritorio 1"
    k_change_config "kglobalshortcutsrc" "kwin" "Window to Desktop 4" "Meta+$,none,Ventana al escritorio 1"

    # Aplicar
    qdbus org.kde.KWin /KWin reconfigure
    killall kglobalaccel5
    kglobalaccel5 &
fi
