#!/bin/bash

if [ $# -eq 1 ]; then
    if [ $1 == "-g" ]; then
        setxkbmap pro -option caps:swapescape
        sed -i "s|^# bindkey -v|bindkey -v|" ${ZDOTDIR:-$HOME}/.zshrc
        sed -i 's|"vim.disableExtension": true,|"vim.disableExtension": false,|' /home/gabriel/.config/Code/User/settings.json
    elif [ $1 == "-c" ]; then
        setxkbmap latam -option
        sed -i "s|^bindkey -v|# bindkey -v|" ${ZDOTDIR:-$HOME}/.zshrc
        sed -i 's|"vim.disableExtension": false,|"vim.disableExtension": true,|' /home/gabriel/.config/Code/User/settings.json
    fi
fi
