#!/bin/bash

ruta=/home/gabriel/Programación/dotfiles

if [ $# -ne 1 ]; then
    exit
else
    if [[ $1 == "-o" ]]; then
        # Plasma
        lookandfeeltool -a org.kde.breezedark.desktop >/dev/null 2>&1
        lookandfeeltool -a org.kde.breezedark.desktop >/dev/null 2>&1

        # Alacritty
        sed -i "s|^colors:.*|colors: *dark|" $ruta/alacritty/.config/alacritty/alacritty.yml

        # Google Chrome
        sed -i "s|^--$|--enable-features=WebUIDarkMode|" $ruta/chrome/.config/chrome-flags.conf
        sed -i "s|^##$|--force-dark-mode|" $ruta/chrome/.config/chrome-flags.conf

        # Visual Studio Code
        sed -i 's|"workbench.colorTheme": .*|"workbench.colorTheme": "Atom One Dark",|' /home/gabriel/.config/Code/User/settings.json

        # Neovim
        sed -i "s|background = .*|background = 'dark'|" $ruta/neovim/.config/nvim/init.lua

        # Tmux
        sed -i "s|'bg=.*|'bg=#282c34'|" $ruta/tmux/.config/tmux/tmux.conf
        sed -i "s|'fg=.*|'fg=#abb2bf'|" $ruta/tmux/.config/tmux/tmux.conf
        tmux source-file $ruta/tmux/.config/tmux/tmux.conf

    elif [[ $1 == "-c" ]]; then
        # Plasma
        lookandfeeltool -a org.kde.breeze.desktop >/dev/null 2>&1
        lookandfeeltool -a org.kde.breeze.desktop >/dev/null 2>&1

        # Alacritty
        sed -i "s|^colors:.*|colors: *light|" $ruta/alacritty/.config/alacritty/alacritty.yml

        # Google Chrome
        sed -i "s|^--enable-features=WebUIDarkMode|--|" $ruta/chrome/.config/chrome-flags.conf
        sed -i "s|^--force-dark-mode|##|" $ruta/chrome/.config/chrome-flags.conf

        # Visual Studio Code
        sed -i 's|"workbench.colorTheme": .*|"workbench.colorTheme": "Atom One Light",|' /home/gabriel/.config/Code/User/settings.json

        # Neovim
        sed -i "s|background = .*|background = 'light'|" $ruta/neovim/.config/nvim/init.lua

        # Tmux
        sed -i "s|'bg=.*|'bg=#fafafa'|" $ruta/tmux/.config/tmux/tmux.conf
        sed -i "s|'fg=.*|'fg=#6a6a6a'|" $ruta/tmux/.config/tmux/tmux.conf
        tmux source-file $ruta/tmux/.config/tmux/tmux.conf

    fi
fi
